### ISSUE TITLE
System conversion to laravel -- Conversão do sistema para laravel

### ISSUE THREAD

**Issue by lucaoyz** [lucaoyz/Sistema-Laravel#1]
## **Conversão do sistema para laravel**

**_Coisas a fazer:_**

**0. Excluir views desnecessárias do template.**
- [x] rtl.blade.php (Arábe)
- [x] virtual-reality.blade.php (Realidade virtual)

**1. Converter todas as views do template para laravel.** 
- [x] dashboard.blade.php
- [x] sign-in.blade.php
- [x] billing.blade.php
- [x] notifications.blade.php
- [x] profile.blade.php
- [x] sign-up.blade.php
- [x] tables.blade.php

**2. Criar ou alterar views necessárias para o sistema.**
- [x] dashboard
- [x] usuarios
- [x] clientes
- [x] financeiro
- [x] produtos
- [x] estoque
- [x] fornecedores
- [x] logistica
- [x] login
- [x] registro
- [x] perfil
- [x] notificacoes

_**Imagem para referencia da pasta views**_
![image](https://user-images.githubusercontent.com/67985413/156464099-2a2ba97d-d5c9-4d30-b7a9-355b7acea5ca.png)

**3. Definir rotas e controllers somente para as views necessárias para o sistema, excluir o restante.**
- [x] dashboard
- [x] usuarios
- [x] financeiro
- [x] login
- [x] registro
- [x] perfil
- [x] treino

_**Imagem para referencia da pasta controllers, routes e arquivo web.php**_
![image](https://user-images.githubusercontent.com/67985413/156464242-6cc0416f-c7bb-4a88-b45d-f9c248f38f28.png)

![image](https://user-images.githubusercontent.com/67985413/156464388-0ec90813-7eba-4d74-a1c2-b2932d8d5b36.png)

**4. Criar e introduzir method @yield ao blade de cada view.**
- [x] head
- [x] navbar header
- [x] navbar side left
- [x] footer
- [x] settings (navbar side right)

_**Imagem de exemplo para referencia de @yield **_
![image](https://user-images.githubusercontent.com/67985413/156464515-14f429f0-1c68-45f6-94de-58308a7bd9cb.png)

**5. Conversão concluída.**
- [x] Conversão concluída.

**Comment by lucaoyz** [comment]
Mudança de planos dia 30/03, deletar alguns itens da Checklist a fazer e acrescentar outros. (tudo continua normalmente)

**Comment by lucaoyz** [comment]
![image](https://user-images.githubusercontent.com/67985413/161591237-514d6122-d30b-4b15-922b-6873e3e421ba.png)
SECTIONS

**Comment by lucaoyz** [comment]
![image](https://user-images.githubusercontent.com/67985413/161594368-991577fe-f59d-4e3a-af4e-9cc8aee69329.png)
Sections
ENDSECTION ACIMA DO /MAIN

**Comment by lucaoyz** [comment]
![image](https://user-images.githubusercontent.com/67985413/161594574-708d10e0-1ee1-44ad-a6af-e1c8a8403819.png)
**Traduzir/Modificar o restante da navbar/sidebar/footer/settings**

- [x] Concluido.
Após isso, voltar acima e marcar Conversão concluida, e fechar issue.

**Comment by AbnerGBS** [comment]
termine

**Comment by lucaoyz** [comment]
> termine

terminado
